# Generated by Django 4.2.17 on 2024-12-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_remove_sign_up_password_alter_sign_up_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
