# Generated by Django 4.2.17 on 2024-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_alter_sign_up_email_alter_sign_up_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='password',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
