# Generated by Django 4.2.17 on 2024-12-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0008_alter_sign_up_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='checkbox',
        ),
    ]
