# Generated by Django 4.2.17 on 2024-12-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0009_remove_sign_up_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='username',
            new_name='usernamel',
        ),
    ]
