# Generated by Django 4.2.17 on 2024-12-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0010_rename_username_sign_up_usernamel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='usernamel',
            new_name='username',
        ),
    ]
